### ISSUE TITLE
Write tutorial on deploying with Docker

### ISSUE THREAD

**Issue by alvancamp** [nodecg/docs#9]
NodeCG's Docker image builds: https://hub.docker.com/r/nodecg/nodecg/tags/

Example `docker-compose.yml`:
```yml
version: '2'
services:
  nodecg:
    image: nodecg/nodecg:v1.0.0
    volumes:
      - "/home/username/nodecg/bundles:/usr/src/app/bundles:rw"
      - "/home/username/nodecg/cfg:/usr/src/app/cfg:ro"
      - "/home/username/nodecg/logs:/usr/src/app/logs:rw"
      - "/home/username/nodecg/db:/usr/src/app/db:rw"
      - "/home/username/nodecg/assets:/usr/src/app/assets:rw"
    environment:
      VIRTUAL_HOST: nodecg.example.net
    restart: always
  proxy:
    image: jwilder/nginx-proxy
    volumes:
      - "/var/run/docker.sock:/tmp/docker.sock"
      - "/home/username/.ssl:/etc/nginx/certs"
      - "/home/username/vhost.d:/etc/nginx/vhost.d:ro"
    ports:
      - "80:80"
      - "443:443"
    links:
      - nodecg
    restart: always
```

### Summary
NodeCG's core runs in the Docker container, but basically everything that touches the filesystem is expected to be in the host filesystem, and linked into the container as `volumes`. This lets the sysadmin still easily update/add/remove bundles, check logs, save their configs and replicants between deployments, etc.

For online deployment, `jwilder/nginx-proxy` is used to reverse proxy the NodeCG instance and easily get it online and optionally use HTTPS/SSL. That's what the `/home/username/.ssl:/etc/nginx/certs` volume is for.

The `vhost.d` mount is where you can put per-submain nginx configs. For example, `/home/username/vhost.d/nodecg.example.com` could be something like this, used to raise the max file upload limit:
```
client_max_body_size 356m;
proxy_read_timeout 1200;
```
